image: rust:1.35.0-stretch

lint:
  script:
    - rustup component add clippy
    - cargo clippy --all -- -D warnings

style-check:
  script:
    - rustup component add rustfmt
    - find src -type f -name "*.rs" | xargs rustfmt --check
test:
  script:
    - cargo test
