lint:
  stage: test
  image: rust:1.81.0-bullseye
  needs: []
  script:
    - rustup component add clippy
    - cargo clippy --all -- -D warnings
style-check:
  stage: test
  image: rust:1.81.0-bullseye
  needs: []
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
test:
  stage: test
  image: rust:1.81.0-bullseye
  needs: []
  script:
    - cargo test
