image: rust:1.34.1-stretch

cache:
  key: "shared-cargo-cache"
  paths:
    - "$HOME/.cargo"

lint:
  script:
    - rustup component add clippy
    - cargo clippy --all -- -D warnings

test:
  script:
    - cargo test
