
lint:
  image: rust:1.43.0-stretch
  script:
    - rustup component add clippy
    - cargo clippy --all -- -D warnings
style-check:
  image: rust:1.43.0-stretch
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
test:
  image: rust:1.40.0-stretch
  script:
    - cargo test
