[package]
name = "typeracer"
version = "0.1.0"
authors = ["DarrienG <darrienglasser@outlook.com>"]
edition = "2018"

[dependencies]
tui = { path = "../tui-rs" }
termion = "1.5"
unicode-width = "0.1.5"
