[package]
name = "typeracer"
version = "0.1.0"
authors = ["DarrienG <darrienglasser@outlook.com>"]
edition = "2018"

[dependencies]
# Temporarily use fork while waiting for clone in Text
tui = { git = "https://github.com/DarrienG/tui-rs.git" }
termion = "1.5"
unicode-width = "0.1.5"
flate2 = "1.0"
