[package]
name = "typeracer"
version = "0.1.0"
authors = ["DarrienG <darrienglasser@outlook.com>"]
edition = "2018"

[dependencies]
# Temporarily use fork while waiting for clone in Text
tui = { git = "https://github.com/darrieng/tui-rs", branch = "master" }
termion = "1.5"
unicode-width = "0.1.5"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin15-gcc"
ar = "x86_64-apple-darwin15-ar"
